apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
spec:
  tasks:
  - name: git-clone
    params:
    - name: repo-url
      value: https://github.com/anilabhabaral/hello-cicd-argocd-jboss.git
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace-test
  - name: maven-build
    params:
    - name: maven-image
      value: registry.access.redhat.com/ubi8/openjdk-11:1.18-2
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: maven-build
    workspaces:
    - name: source
      workspace: workspace-test
  - name: build-and-push-to-openshift-registry
    params:
    - name: image-name
      value: hello
    - name: image-tag
      value: $(context.pipelineRun.uid)
    - name: dockerfile-path
      value: Dockerfile
    - name: internal-registry
      value: default-route-openshift-image-registry.apps.cndsno3.cee.ral3.lab.eng.rdu2.redhat.com
    - name: namespace
      value: testpipeline
    - name: buildah-image
      value: quay.io/buildah/stable:v1.17.0
    runAfter:
    - maven-build
    taskRef:
      kind: Task
      name: build-and-push-to-openshift-registry
    workspaces:
    - name: source
      workspace: workspace-test
  - name: scale-0
    runAfter:
    - build-and-push-to-openshift-registry
    taskRef:
      kind: Task
      name: scale-0
  workspaces:
  - name: workspace-test
